---
  - name: install subversion related packages
    yum: name={{ item }} state=installed
    with_items:
      - gcc
      - bzip2
      - openssl
      - openssl-devel
      - expat
      - expat-devel
